### ISSUE TITLE
about h5 file key

### ISSUE THREAD

**Issue by baeseongsu** [rajpurkarlab/CheXzero#2]
Hello, thank you for sharing the code.
There seems to be one problem loading the h5 file into the `CXRdataset` class.
Wouldn't the key value be `cxr` rather than `cxr_unprocessed` in L39 (also, L42)?

https://github.com/rajpurkarlab/CheXzero/blob/c303e5c6a3c6d3cef64e3dc51214b09ce7912076/train.py#L24-L43

**Comment by rajpurkar** [comment]
@ekkin2

**Comment by dh58319** [comment]
I have got same issue. is there any solution or workaround??

**Comment by ekkin2** [comment]
Hi thank you for bringing this to our attention. Yes, I believe the key should in fact be "cxr", resolved this issue with 5c341db0fe0db2f663a2c136c7120a8b303f1d11.
