### ISSUE TITLE
Preprocessing in `img_to_h5` fails with resolution other than 320

### ISSUE THREAD

**Issue by nai62** [rajpurkarlab/CheXzero#3]
Hi, thank you for sharing your excellent work.
I found that the preprocessing in `img_to_h5` function fails when I passed `resolution` argument. Probably the cause is in the following line.

https://github.com/rajpurkarlab/CheXzero/blob/809d6f961cb2cce0d4020b0e09b2e491af068461/preprocess_padchest.py#L186

Should be:
```
img = preprocess(img_pil, desired_size=resolution)
```

**Comment by rajpurkar** [comment]
@ekkin2

**Comment by ekkin2** [comment]
Hi @nai62 thank you for brining this to our attention. Resolved with 353fbc0390412c9c98166d70b9900ecaef3a7dea
